// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzujjvoarqqqsgouffac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6dWpqdm9hcnFxcXNnb3VmZmFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODQ4NzYsImV4cCI6MjA3Mzg2MDg3Nn0.6I6LCzuUSQdsb02HTHzAol8P5g8bpXWVIIM2r4d85DA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});